name: Check Format

on:
  pull_request:
    types:
    - opened
    branches:
      - main

    paths-ignore:
    - ".github/workflows/*"
    - ".github/*.md"

jobs:
  Format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.21"]
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check code Format
        run: go fmt
